services:
  - type: web
    name: eventforge-api
    runtime: node
    region: oregon
    plan: starter
    branch: main
    buildCommand: cd backend && npm install --include=dev && npx prisma generate --schema=../prisma/schema.prisma && npm run build
    startCommand: cd backend && npm start
    healthCheckPath: /api/v1/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: DATABASE_URL
        sync: false
      - key: API_KEY_SECRET
        sync: false
      - key: NEXT_PUBLIC_STACK_PROJECT_ID
        sync: false
      - key: NEXT_PUBLIC_STACK_PUBLISHABLE_CLIENT_KEY
        sync: false
      - key: STACK_SECRET_SERVER_KEY
        sync: false
      - key: CORS_ORIGIN
        sync: false
      - key: LOG_LEVEL
        value: info
